version: '2.1'

services:

  vmware-exporter:
    image: pryorda/vmware_exporter:v0.11.1
    container_name: vmware-exporter
    restart: unless-stopped
    ports:
       - '9272:9272'
    expose:
       - 9272
    environment:
      VSPHERE_HOST: "vcenter_ip"
      VSPHERE_IGNORE_SSL: "True"
      VSPHERE_USER: "username"
      VSPHERE_PASSWORD: "password"
    labels:
      org.label-schema.group: "monitoring"
